/**
 * Action types.
 * @module constants/ActionTypes
 */

export const AUTHORIZE = 'AUTHORIZE';
export const APP_CONFIG = 'APP_CONFIG';
export const CONSENT = 'CONSENT';
export const GET_SERVICE_PROVIDER = 'GET_SERVICE_PROVIDER';
export const POLICIES_LOAD = 'POLICIES_LOAD';
export const POLICIES_SAVE = 'POLICIES_SAVE';
export const TEMPLATES_LOAD = 'TEMPLATES_LOAD';
export const PROFILE_LOAD = 'PROFILE_LOAD';
export const PLACE_ADD = 'PLACE_ADD';
export const ADDRESS_SUGGESTION_UPDATE = 'ADDRESS_SUGGESTION_UPDATE';
export const ADDRESS_SUGGESTIONS_LOAD = 'ADDRESS_SUGGESTIONS_LOAD';
export const ADDRESS_SUGGESTIONS_RESET = 'ADDRESS_SUGGESTIONS_RESET';
export const RESIDENTS_LOAD = 'RESIDENTS_LOAD';
export const SERVICES_LOAD = 'SERVICES_LOAD';
export const ALL_SERVICES_LOAD = 'ALL_SERVICES_LOAD';
export const LOCATION_LOAD = 'LOCATION_LOAD';
export const DISPLAY_NAME_LOAD = 'DISPLAY_NAME_LOAD';
export const USER_SESSION_LOGIN = 'USER_SESSION_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
